### ISSUE TITLE
[Task] 글쓰기 페이지 구현

### ISSUE THREAD

**Issue by lvest** [codestates/CoKkiriMarket#21]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 글쓰기 페이지 구현

### TODO
1. [ ] 글쓰기 페이지 템플릿 작성
2. [ ] 상품 가격 및 빈 input에 대한 유효성 검사
3. [ ] 사진 등록 시 미리보기 구현

### Estimated time
`3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__2__`
- Urgency: `Middle`
