### ISSUE TITLE
[Task] socket.io 를 이용한 채팅기능 구현

### ISSUE THREAD

**Issue by onewithtruth** [codestates/CoKkiriMarket#23]
### ISSUE
- Group: `client`, `server`
- Type: `bug`, `feature`, `delete`
- Detail: socket.io 를 이용해 실시간 통신 및 채팅 기능 구현

### TODO
1. [ ] 채팅 로그를 위한 서버 사이드 데이터 베이스 구현
2. [ ] 실시간 채팅 기능 구현
3. [ ] 클라이언트 사이드 UI 구성 및 데이터 베이스 연동

### Estimated time
`3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`, `server`
- Sprint: `Sprint_2`
- Urgency: `High`
