### ISSUE TITLE
[Task] S3(클라우드플레어)로 파일 업로드 및 API 셋업

### ISSUE THREAD

**Issue by onewithtruth** [codestates/CoKkiriMarket#9]
### ISSUE
- Group: `client`, `server`
- Type: `bug`, `feature`, `delete`
- Detail: 이미지 파일 업로드, 업로드된 파일 로드, 로드된 파일 화면에 렌더링.

### TODO
1. [ ] backend: API setup
2. [ ] frontend: client setup
3. [ ] image resizing, client side optimization.

### Estimated time
`3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`, `server`
- Sprint: `Sprint_2`
- Urgency: `High`
